import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useContractRead } from "wagmi";
import VaultFactory from "../../out/AIMVaultFactory.sol/AIMVaultFactory.json";

const Home: NextPage = () => {
  const [vaults, setVaults] = useState<any[]>([]);

  useContractRead({
    addressOrName: "0x81BE49C9584aA772d3005778D3c814cD1A90D179",
    contractInterface: VaultFactory.abi,
    functionName: "vaults",
    args: "0xd87ba7a50b2e7e660f678a895e4b72e7cb4ccd9c",
    onSettled(data, error) {
      if (error) console.log("error", error);
      setVaults((p) => [...p, data]);
    },
  });

  return (
    <div>
      <Head>
        <title>Yield Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Yield Farm</h1>

      <main></main>
    </div>
  );
};

export default Home;
