import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { MouseEventHandler, useCallback, useState, MouseEvent } from "react";
import { useContractRead, useAccount, useContractReads } from "wagmi";
import VaultFactory from "../../out/AIMVaultFactory.sol/AIMVaultFactory.json";
import Vault from "../../out/AIMVault.sol/AIMVault.json";
import Spinner from "../components/spinner";
import { BigNumber } from "ethers";
import DepositModal from "../components/DepositModal";

const Home: NextPage = () => {
  const [vaults, setVaults] = useState<any[]>([]);
  const [myVaults, setMyVaults] = useState<any[]>([]);
  const [underlying, setUnderlying] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const { isConnected } = useAccount();

  const { address } = useAccount();

  useContractRead({
    addressOrName: "0x81BE49C9584aA772d3005778D3c814cD1A90D179",
    contractInterface: VaultFactory.abi,
    functionName: "vaults",
    args: "0xd87ba7a50b2e7e660f678a895e4b72e7cb4ccd9c",
    onSettled(data, error) {
      if (error) console.log("error", error);
      setVaults([data]);
      setIsLoading(false);
    },
  });

  useContractRead({
    addressOrName: vaults[0],
    contractInterface: Vault.abi,
    functionName: "balanceOf",
    args: address,
    onSettled(data, error) {
      if (error) console.log("error", error);

      if (data) {
        let balance = parseInt(data?.toString());
        balance > 0 && setMyVaults((p) => [...p, vaults[0]]);
      }
      console.log("vault bal", data?.toString());
    },
  });

  const { data } = useContractReads({
    contracts: [
      {
        addressOrName: vaults[0],
        contractInterface: Vault.abi,
        functionName: "name",
      },
      {
        addressOrName: vaults[0],
        contractInterface: Vault.abi,
        functionName: "getCompStrategyInfo",
      },
      {
        addressOrName: vaults[0],
        contractInterface: Vault.abi,
        functionName: "totalAssets",
      },
      {
        addressOrName: vaults[0],
        contractInterface: Vault.abi,
        functionName: "UNDERLYING",
      },
    ],
    onSettled(data, error) {
      if (error) console.log("error", error);
      console.log("success", data);
      if (data) {
        setUnderlying(String(data[3]));
      }
    },
  });

  const handleDeposit = (e: MouseEvent<HTMLButtonElement>) => {};

  console.log("render");
  // console.log(isLoading);

  return (
    <main>
      <Head>
        <title>Yield Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Yield Farm</h1>

      <section>
        <h2>My Vaults</h2>
        {myVaults ? (
          myVaults.map((vault) => (
            <div key={vault} className="p-2">
              <p>{data?.[0] && data[0]}</p>
              <p>
                APY:{" "}
                {data?.[1] &&
                  `${(
                    (Math.pow((data[1][1].toNumber() / 1e18) * 6570 + 1, 365) -
                      1) *
                    100
                  ).toFixed(2)}%`}
              </p>
              <p>
                Total Assets:{" "}
                {data?.[2] && `${data[2].div(BigNumber.from(String(1e18)))}`}
              </p>
              <DepositModal vault={vaults[0]} underlying={underlying} />
            </div>
          ))
        ) : (
          <div>
            <p>You haven&#39;t deposited in any vaults</p>
            <p>FInd and deposit in a vault</p>
          </div>
        )}
      </section>

      <section>
        <h2>All Vaults</h2>

        <div>
          {isLoading ? (
            <Spinner />
          ) : (
            vaults.map((vault) => (
              <div key={vault} className="p-2">
                <p>{data?.[0] && data[0]}</p>
                <p>
                  APY:{" "}
                  {data?.[1] &&
                    `${(
                      (Math.pow(
                        (data[1][1].toNumber() / 1e18) * 6570 + 1,
                        365
                      ) -
                        1) *
                      100
                    ).toFixed(2)}%`}
                </p>
                <p>
                  Total Assets:{" "}
                  {data?.[2] && `${data[2].div(BigNumber.from(String(1e18)))}`}
                </p>
                <DepositModal vault={vaults[0]} underlying={underlying} />
              </div>
            ))
          )}
        </div>
      </section>
    </main>
  );
};

export default Home;
