import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useContractRead, useAccount, useContractReads } from "wagmi";
import VaultFactory from "../../out/AIMVaultFactory.sol/AIMVaultFactory.json";
import Vault from "../../out/AIMVault.sol/AIMVault.json";
import Spinner from "../components/spinner";

const Home: NextPage = () => {
  const [vaults, setVaults] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { address, isConnected } = useAccount();

  useContractRead({
    addressOrName: "0x81BE49C9584aA772d3005778D3c814cD1A90D179",
    contractInterface: VaultFactory.abi,
    functionName: "vaults",
    args: "0xd87ba7a50b2e7e660f678a895e4b72e7cb4ccd9c",
    onSettled(data, error) {
      if (error) console.log("error", error);
      setVaults([data]);
      setIsLoading(false);
    },
  });

  useContractReads({
    contracts: [
      {
        addressOrName: vaults[0],
        contractInterface: Vault.abi,
        functionName: "totalAssets",
      },
      {
        addressOrName: vaults[0],
        contractInterface: Vault.abi,
        functionName: "getCompStrategyInfo",
      },
    ],
    onSettled(data, error) {
      if (error) console.log("error", error);
      console.log("success", data);
    },
  });

  console.log("render");
  // console.log(isLoading);

  return (
    <main>
      <Head>
        <title>Yield Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Yield Farm</h1>

      <section>
        <h2>My Vaults</h2>
        {isConnected ? (
          <div>your vaults</div>
        ) : (
          <div>
            <p>You haven&#39;t deposited in any vaults</p>
            <p>FInd and deposit in a vault</p>
          </div>
        )}
      </section>

      <section>
        <h2>All Vaults</h2>

        <div>
          {isLoading ? (
            <Spinner />
          ) : (
            vaults.map((vault) => (
              <div key={vault} className="p-2">
                <p>Assest: </p>
                <p>APY: </p>
                <p>Total Assets</p>
                <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-3 rounded">
                  deposit
                </button>
              </div>
            ))
          )}
        </div>
      </section>
    </main>
  );
};

export default Home;
